package form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import movie.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author greggjs
 */
public class NewAccountPage extends javax.swing.JFrame {
    public Main main;
    /**
     * Creates new form NewAccountPage
     */
    public NewAccountPage(Main main) {
        this.main = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        ConfirmPWField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CreditCardField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Create a New Account");
        setBounds(java.awt.Toolkit.getDefaultToolkit().getScreenSize().width/2 - 200, java.awt.Toolkit.getDefaultToolkit().getScreenSize().height/2-200, 0, 0);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                WindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 100, 123));
        jPanel1.setPreferredSize(new java.awt.Dimension(317, 300));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name: ");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone Number:");

        jButton1.setBackground(new java.awt.Color(0, 100, 123));
        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 100, 123));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Create Account");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Credit Card");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmPWField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(NameField)
                    .addComponent(PhoneField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CreditCardField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreditCardField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPWField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = NameField.getText();
        String phone = PhoneField.getText();
        String credit_card = CreditCardField.getText();
        char[] pwd_arr = PasswordField.getPassword();
        String pwd = new String (pwd_arr);
        char[] cpwd_arr = ConfirmPWField.getPassword();
        String cpwd = new String (cpwd_arr);
        String select_bank = "SELECT renter_phone FROM Renter where renter_phone = '" + phone + "'";
        String bank = "insert into Renter values ('"+phone +"', '"+name+"','"+credit_card+"','"+pwd+"')";
        String phone_check = null;
        String test = null;
        
        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, 
                    "Please enter your name"
                    + "\nError: NullName");
            return;
        }
        
        if (!checkPhone(phone))
            return;
        else if (!checkCC(credit_card))
            return;
        else if (!checkPwd(pwd, cpwd))
            return;
        
        test = selectStm(select_bank, "renter_phone");
        
        if (test==null) {
            
            prepStm(bank);
              
            main.curr = new Renter(name, phone);
            this.setVisible(false);
            main.loginUserFrame.setVisible(true);
            
        } else {
             JOptionPane.showMessageDialog(this,
                    "User already exists\nError: UsrExists");
            this.NameField.setText("");
            this.PhoneField.setText("");
            this.CreditCardField.setText("");
            this.PasswordField.setText("");
            this.ConfirmPWField.setText("");
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WindowClosing
        // TODO add your handling code here:
        this.NameField.setText("");
        this.PhoneField.setText("");
        this.CreditCardField.setText("");
        this.PasswordField.setText("");
        this.ConfirmPWField.setText("");
        main.frame.setVisible(true);
    }//GEN-LAST:event_WindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.NameField.setText("");
        this.PhoneField.setText("");
        this.CreditCardField.setText("");
        this.PasswordField.setText("");
        this.ConfirmPWField.setText("");
        this.setVisible(false);
        main.frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void prepStm(String bank) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3307/fall2012"
                    + "?user=greggjs&password=greggjs");
            PreparedStatement stm = conn.prepareStatement(bank);
            stm.execute();
        } catch (SQLException e) {
            System.out.println("SQL Error 2");
            return;
        } catch (ClassNotFoundException err) {
            System.out.println ("Problem!");
        }
    }
    
    public String selectStm(String bank, String type) {
        String res = null;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3307/fall2012?"
                    + "user=greggjs&password=greggjs");
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(bank);
            while (rs.next()) {
                res = rs.getString(type);
            }
        } catch (SQLException e) {
            System.out.println("SQL Error 1");
        } catch (ClassNotFoundException err) {
            System.out.println ("Problem!");
        }
        
        return res;
    }
    
    public boolean checkPhone(String phone) {
        
        try {
            Long.parseLong(phone);
            if (phone.equals("")) {
                JOptionPane.showMessageDialog(this, 
                    "Please enter your phone #"
                    + "\nError: NullPhone");
                return false;
            }
            else if (phone.length()!=10) {
                JOptionPane.showMessageDialog(this, 
                    "Please enter a valid phone number"
                    + "\nExample: 5557776546"
                    + "\nError: IncrtPhone");
                return false;
            }
            return true;
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(this, 
                    "Please enter a valid phone #\n"
                    + "Example:5554443333"
                    + "\nError: NumFormat");
            PhoneField.setText("");
            return false;
        }
        
    }
    
    public boolean checkCC(String credit_card) {
        
        try {
            Long.parseLong(credit_card);
            if (credit_card.equals("")) {
                JOptionPane.showMessageDialog(this, 
                    "Please enter your credit card"
                    + "\nError: NullCrCd");
                return false;
            }
            else if (credit_card.length()!=16) {
                JOptionPane.showMessageDialog(this, 
                    "Please enter a vlid credit card"
                    + "\nExample: 4444777788885555"
                    + "\nError: IncrtCrCd");
                return false;
            }
            return true;
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(this, 
                    "Please enter a credit card #\n"
                    + "Example:5555111188889999"
                    + "\nError: NumFormat");
            CreditCardField.setText("");
            return false;
        }    
    }
    
    public boolean checkPwd(String pwd, String cpwd) {
        
        if (pwd.equals("")) {
            JOptionPane.showMessageDialog(this, 
                    "Please enter your password"
                    + "\nError: NullPwd");
            return false;
        }
        else if (cpwd.equals("")) {
            JOptionPane.showMessageDialog(this, 
                    "Please confirm your password"
                    + "\nError: NullPwdCon");
            return false;
        } 
        
        else if (!pwd.equals(cpwd)) {
            JOptionPane.showMessageDialog(this, 
                    "Please enter your password "
                    + "correctly both times\nError: PwdMismatch");
            return false;
        } 
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPWField;
    private javax.swing.JTextField CreditCardField;
    private javax.swing.JTextField NameField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
